Feature/002
Programeiros/ThisFinans pull request #6
Opened 2022-09-10 14:54 UTC by thiagodd

2# Peço que baixem o projeto na maquina de vcs e testem antes de aprovar o PR.

2022-09-10 15:25 UTC, brunosilvaJava requested changes

2022-09-10 15:25 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/TypeTransactions.java
> +public enum TypeTransactions {
O que acha de alterar para TransactionsType?

2022-09-10 15:25 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/TypeUser.java
> +public enum TypeUser {
Mesmo do transactions

2022-09-10 15:25 UTC, brunosilvaJava commented on thisfinans/src/main/resources/application.yml
>  spring:
Adiciona a validação da estrutura do banco

spring: jpa: hibernate: ddl-auto: validate

2022-09-10 16:00 UTC, brunosilvaJava commented on thisfinans/pom.xml
> +			<artifactId>hibernate-validator</artifactId>
Qual é a função dessa dependência?

2022-09-11 10:45 UTC, Thiagosilvadd commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/TypeTransactions.java
> +public enum TypeTransactions {
De acordo. Corrigindo!

2022-09-11 10:48 UTC, closed without merging