Feature/002
Programeiros/ThisFinans pull request #7
Opened 2022-09-11 10:53 UTC by thiagodd

Foram realizada as correções que o Bruno indicou. Enviando a PT novamente.

2022-09-11 14:27 UTC, brunosilvaJava requested changes
O projeto não está compilando.

2022-09-11 14:27 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/UserType.java
> +public enum TypeUser {
faltou renomear o nome aqui no enum, foi alterado apenas no nome do arquivo

2022-09-11 14:27 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/UserType.java
> +public enum TypeUser {
o projeto não está compilando

2022-09-11 14:27 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/AccountType.java
> +public enum TypeAccount {
mesmo dos outros

2022-09-11 14:27 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/TransactionsType.java
> +public enum TypeTransactions {
mesmo dos outros

2022-09-11 14:27 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/UserType.java
> +public enum TypeUser {
https://www.facebook.com/IntelliJIDEA/videos/you-can-rename-packages-classes-interfaces-enums-or-variable-names-with-ease-in-/888467681568491/

2022-09-11 14:27 UTC, brunosilvaJava commented on thisfinans/src/main/resources/application.yml
>  spring:
adiciona  -  hibernate: ddl-auto: validate

https://www.baeldung.com/spring-boot-data-sql-and-schema-sql

```suggestion
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thisfinansdb
    username: root
    password: 1234567
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
```

2022-09-11 14:40 UTC, brunosilvaJava requested changes

2022-09-11 14:40 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/Account.java
> +    List<Transactions> Transactions;
add private

2022-09-11 14:40 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/Account.java
> +    List<TransactionEntries> transactionEntries;
add private

2022-09-11 14:40 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/Account.java
> +    List<Transactions> Transactions;
atributo iniciando com letra maiuscula

2022-09-11 14:42 UTC, brunosilvaJava requested changes

2022-09-11 14:42 UTC, brunosilvaJava commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/Transactions.java
> +    List<TransactionEntries> transactionEntries;
add private

2022-09-11 15:16 UTC, thiagodd commented on thisfinans/src/main/java/com/programeiros/thisfinans/model/entities/ENUM/AccountType.java
> +public enum TypeAccount {
corrigido!

2022-09-11 15:36 UTC, brunosilvaJava submitted a review, later dismissed

2022-09-11 17:40 UTC, mmacedoaraujo approved these changes, later dismissed

2022-09-12 01:21 UTC, brunosilvaJava approved these changes

2022-09-12 01:36 UTC, mmacedoaraujo approved these changes

2022-09-12 01:59 UTC, merged